name: Ubuntu (from source)

on:
  workflow_dispatch:
    inputs:
      root-version-major:
        required: true
        description: ROOT Major version number (string) according to `Major.Minor.Patch` schema
        default: "6"
      root-version-minor:
        required: true
        description: ROOT Minor version number (string) according to `Major.Minor.Patch` schema
        default: "26"
      root-version-patch:
        required: true
        description: ROOT Patch version number (string) according to `Major.Minor.Patch` schema
        default: "02"

jobs:
  build-and-push-ubuntu-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      ROOT_VERSION_STRING: ${{ github.event.inputs.root-version-major }}.${{ github.event.inputs.root-version-minor }}.${{ github.event.inputs.root-version-patch }}

    steps:
      - name: Print Image name with tag(s)
        run: |
          echo "Image name with tag: ${{ env.IMAGE_NAME_WITH_TAG }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: ubuntu_from_source/
          pull: true
          push: true
          build-args: |
            ROOT_VERSION=${{ env.ROOT_VERSION_STRING }}
          tags: ghcr.io/${{ github.repository_owner }}/root:${{ env.ROOT_VERSION_STRING }}-ubuntu-from-source
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
